# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Copy project files
COPY . /app

# Upgrade pip and install package with dependencies
RUN pip install --upgrade pip setuptools wheel \
    && pip install --no-cache-dir .

# Ensure unbuffered output
ENV PYTHONUNBUFFERED=1

# Start the MCP server in stdio mode
CMD ["ashare-mcp", "--stdio"]
